[workspace]
resolver = "2"
members = ["dnas/*/zomes/coordinator/*", "dnas/*/zomes/integrity/*"]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[workspace.dependencies]
hdi = "0.4.0-beta-dev.30"
hdk = "0.3.0-beta-dev.34"
holochain = "0.3.0-beta-dev.40"
serde = "1.0.193"
