[workspace]
resolver = "2"
members = ["dnas/*/zomes/coordinator/*", "dnas/*/zomes/integrity/*"]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[workspace.dependencies]
hdi = "0.5.0-dev.2"
hdk = "0.4.0-dev.2"
serde = "1"
holochain = "0.4.0-dev.2"
