[package]
edition = "2018"
name = "syn_integrity"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "syn_integrity"

[dependencies]
derive_more = "0"
serde = "1"

hc_zome_syn_integrity = { git = "https://github.com/holochain/syn", branch = "main-0.4" }
